[phases.setup]
nixPkgs = [
  'nodejs',
  'pnpm',
  'python3',
  'gcc',
  'g++',
  'make'
]

[phases.install]
cmds = [
  'python3 --version',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm migrate:deploy',
  'pnpm build'
]

[start]
cmd = 'pnpm dev'