[phases.setup]
aptPkgs = [
  "python3",
  "build-essential",
  "make",
  "gcc",
  "g++",
  "nodejs",
  "openssl"
]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  # Create self-hosting env file with Railway variables
  "echo 'NODE_ENV=production' > self-hosting/.env",
  "echo 'SELF_HOSTED=true' >> self-hosting/.env",
  "echo 'GEO_IP_HOST=http://op-geo:8080' >> self-hosting/.env",
  "echo 'BATCH_SIZE=5000' >> self-hosting/.env",
  "echo 'BATCH_INTERVAL=10000' >> self-hosting/.env",
  "echo 'REDIS_URL=${REDIS_URL}' >> self-hosting/.env",
  "echo 'CLICKHOUSE_URL=${CLICKHOUSE_URL}' >> self-hosting/.env",
  "echo 'DATABASE_URL=${DATABASE_URL}' >> self-hosting/.env",
  "echo 'DATABASE_URL_DIRECT=${DATABASE_URL_DIRECT}' >> self-hosting/.env",
  "echo 'NEXT_PUBLIC_DASHBOARD_URL=https://${RAILWAY_PUBLIC_DOMAIN}' >> self-hosting/.env",
  "echo 'NEXT_PUBLIC_API_URL=https://${RAILWAY_PUBLIC_DOMAIN}/api' >> self-hosting/.env",
  "echo 'COOKIE_SECRET=${RESEND_API_KEY}' >> self-hosting/.env",
  # Copy env for build
  "cp self-hosting/.env .env",
  # Build steps
  "pnpm db:codegen",
  "pnpm --filter db run migrate:deploy",
  "pnpm --filter api run build",
  "pnpm --filter public run build"
]

[phases.start]
cmd = "pnpm --filter api start:prod"

[nixpacks]
node-version = "18"
plan = [
  "web"
]