[phases.setup]
aptPkgs = [
  "python3",
  "build-essential",
  "make",
  "gcc",
  "g++",
  "nodejs",
  "openssl"
]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  # Install workspace dependencies
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  # Generate database types
  "pnpm db:codegen",
  # Build the apps
  "pnpm --filter api run build",
  "pnpm --filter public run build"
]

[phases.start]
cmd = "pnpm --filter api start"

[nixpacks]
node-version = "18"