[phases.setup]
aptPkgs = [
  "python3",
  "build-essential",
  "make",
  "gcc",
  "g++",
  "nodejs"
]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm migrate:deploy",
  "pnpm build"
]

[start]
cmd = "pnpm dev"

[nixpacks]
start-command = "pnpm dev"